language: scala
scala:
   - 2.13.0
branches:
  only:
    - master
jdk:
  - oraclejdk11
services:
  - docker
script:
  - sbt clean coverage test coverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)